name: ast.py flake

on:
  push:
    branches: [ "master" ]
    paths:
      - ".github/workflows/**"
      - "ast.py"
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Install flake
        run: python3 -m pip install flake8
      - uses: actions/checkout@v4
      - name: Lint
        run: flake8 ast.py
        continue-on-error: true
